export const pageTypes = Object.freeze({
  ABOUT: 'about',
  ACCESS_CONTROL: 'access_control',
  ALARMS: 'alarms',
  ANTENNAS: 'antennas',
  AUDIO_VIDEO: 'audio_video',
  BARRIERS: 'barriers',
  CONTACT: 'contact',
  DOWNLOAD: 'download',
  ELECTRICITY: 'electricity',
  FIBER_OPTICS: 'fiber_optics',
  GATES: 'gates',
  HOME: 'home',
  INTERCOMS: 'intercoms',
  NOT_FOUND: 'not_found',
  PARKING_SYSTEMS: 'parking_system',
  SECURITY: 'security_systems',
  WORKS: 'works',
});
